service: vision
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "rekognition:DetectLabels"
        - "rekognition:DetectFaces"
        - "s3:GetObject"
      Resource:
        - "*"


functions:
  health:
    handler: handler.health
    events:
      - httpApi:
          path: /
          method: get
  v1Description:
    handler: handler.v1_description
    events:
      - httpApi:
          path: /v1
          method: get
  v1visionDescription:
    handler: handler.v1vision_description
    events:
      - httpApi:
          path: /v1/vision
          method: post
  v2Description:
    handler: handler.v2_description
    events:
      - httpApi:
          path: /v2
          method: get
  v2VisionDescription:
    handler: handler.v2vision_description
    events:
      - httpApi:
          path: /v2/vision
          method: post

resources:
  Resources:
   MeuBucketdeImagens:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: bucket-images-sprint8
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: false
      OwnershipControls: 
        Rules: 
          - ObjectOwnership: ObjectWriter
