service: vision
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - "rekognition:DetectLabels"
        - "rekognition:DetectFaces"
        - "s3:GetObject"
      Resource: 
        - "*"

resources:
  Resources:
    MinhasFotosBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Sub "mycatphotos-${AWS::AccountId}"

    MeusTextosBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Sub "myphotos-${AWS::AccountId}"

functions:
  health:
    handler: src/handler.health
    events:
      - httpApi:
          path: /
          method: get
  v1Description:
    handler: src/handler.v1_description
    events:
      - httpApi:
          path: /v1
          method: get
  v2Description:
    handler: src/handler.v2_description
    events:
      - httpApi:
          path: /v2
          method: get
  v1Vision:
    handler: src/vision1.v1_vision
    events:
      - httpApi:
          path: /v1/vision
          method: post
  v2Vision:
    handler: src/vision2.v2_vision
    events:
      - httpApi:
          path: /v2/vision
          method: post
