Resources:
  AnalyzeImagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: my-bucket
            Events: s3
